### ISSUE TITLE
Google Drive Public Dataset Broken

### ISSUE THREAD

**Issue by RamonYeung** [yuyuz/MetaQA#1]
Hi,

**I find no data under `3-hop/vanilla`, `3-hop/ntm`, `1-hop/vanilla` and `1-hop/ntm` folder.**

Am I missing something in README?

I would like to follow this research direction to finally solve KBQA.

Thank, and great work!

**Comment by yuyuz** [comment]
Hi, I tried the link and it works to access the folders you mentioned. For example,

![image](https://user-images.githubusercontent.com/14950226/38579196-3c61470c-3cd4-11e8-8f15-0045acbe8d32.png)

Could you try to download it again?

**Comment by RamonYeung** [comment]
OK, it works for me now.

GFW may blocks me out.

Thanks.
