### ISSUE TITLE
1-hop ground truth missing

### ISSUE THREAD

**Issue by Crime2321** [yuyuz/MetaQA#5]
First of all, thank you and your colleagues for your efforts in proposing the MetaQA dataset and making a huge contribution to subsequent research on knowledge graph question answering!

We recently discovered that some data in the MetaQA 1-hop test dataset have incomplete Groud Truth. The details are as follows:

For eg. **qid 1444**
Query: who acted in the movie **[The 39 Steps]**?
Ground Truth: **['Robert Donat', 'Madeleine Carroll']**
But in KG, in addition to the above two actors, the movie **The 39 Steps** also has the following actors:
![image](https://github.com/user-attachments/assets/3d980ec2-3553-4ef5-ab98-e7c1a184ceb3)

This error causes the accuracy rate to be falsely low when we use hit@1 as the criterion.
Attached are the 90 1-hop QA data that we have discovered so far that are suspected of this situation, for your reference.
[1-hop_GT_missing.txt](https://github.com/user-attachments/files/16233249/1-hop_GT_missing.txt)

Finally, thank you and your colleagues again for your hard work, and thank you for your precious time!

**Comment by yuyuz** [comment]
Hi @Crime2321, thanks for your interest in our MetaQA dataset, and thank you so much for pointing out this issue. You're more than welcome to release an updated version of MetaQA 1-hop test dataset, and maybe name it as **MetaQA v2** to differentiate from the original one. This will facilitate future researchers that use MetaQA to accurately report their results. I'll also be glad to help add **MetaQA v2** downloading link in our GitHub readme.

**Comment by Crime2321** [comment]
Thanks for your reply!! We will work on this 👍 👍 👍
